def test_protected_endpoint_requires_authentication(): ...


def test_protected_endpoint_rejects_invalid_token(): ...


def test_protected_endpoint_rejects_malformed_token(): ...


def test_protected_endpoint_accepts_valid_token(): ...


def test_inactive_user_cannot_access_protected_endpoint(): ...
