"""Create contracts table

Revision ID: 60ab24c18a51
Revises: 6a826b2e8691
Create Date: 2026-09-16 19:43:04.015859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60ab24c18a51'
down_revision: Union[str, Sequence[str], None] = '6a826b2e8691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('buyer_id', sa.Uuid(), nullable=True),
    sa.Column('land_id', sa.Uuid(), nullable=False),
    sa.Column('crop_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='OPEN', nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['land_id'], ['lands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_buyer_id'), 'contracts', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_contracts_crop_id'), 'contracts', ['crop_id'], unique=False)
    op.create_index(op.f('ix_contracts_farmer_id'), 'contracts', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_contracts_land_id'), 'contracts', ['land_id'], unique=False)
    op.create_index(op.f('ix_contracts_status'), 'contracts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contracts_status'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_land_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_farmer_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_crop_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_buyer_id'), table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
