"""create crops table

Revision ID: 6a826b2e8691
Revises: a01fde1371aa
Create Date: 2026-09-16 17:53:11.157798

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6a826b2e8691"
down_revision: str | Sequence[str] | None = "a01fde1371aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crops",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("farmer_id", sa.Uuid(), nullable=False),
        sa.Column("land_id", sa.Uuid(), nullable=False),
        sa.Column("crop_name", sa.String(length=150), nullable=False),
        sa.Column("season", sa.String(length=100), nullable=True),
        sa.Column("sowing_date", sa.Date(), nullable=True),
        sa.Column(
            "expected_harvest_date",
            sa.Date(),
            nullable=True,
        ),
        sa.Column(
            "expected_yield",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["farmer_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["land_id"],
            ["lands.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("crops")
    # ### end Alembic commands ###
