"""create lands table

Revision ID: a01fde1371aa
Revises: b9ff8813c296
Create Date: 2026-09-16 17:18:16.290593

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a01fde1371aa"
down_revision: str | Sequence[str] | None = "b9ff8813c296"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lands",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("farmer_id", sa.Uuid(), nullable=False),
        sa.Column("land_name", sa.String(length=150), nullable=False),
        sa.Column("village", sa.String(length=150), nullable=True),
        sa.Column("district", sa.String(length=150), nullable=True),
        sa.Column("state", sa.String(length=150), nullable=True),
        sa.Column(
            "area_acres",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
        ),
        sa.Column("soil_type", sa.String(length=100), nullable=True),
        sa.Column(
            "irrigation_type",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["farmer_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lands")
    # ### end Alembic commands ###
