"""Create contract bids table

Revision ID: f14deef3b783
Revises: 60ab24c18a51
Create Date: 2026-09-17 10:40:00.913196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f14deef3b783'
down_revision: Union[str, Sequence[str], None] = '60ab24c18a51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_bids',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('buyer_id', sa.Uuid(), nullable=False),
    sa.Column('offered_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('offered_price_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='PENDING', nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_bids_buyer_id'), 'contract_bids', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_contract_bids_contract_id'), 'contract_bids', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_bids_status'), 'contract_bids', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_bids_status'), table_name='contract_bids')
    op.drop_index(op.f('ix_contract_bids_contract_id'), table_name='contract_bids')
    op.drop_index(op.f('ix_contract_bids_buyer_id'), table_name='contract_bids')
    op.drop_table('contract_bids')
    # ### end Alembic commands ###
